{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "el-GR",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/localhost;ChinookDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost",
            "database": "ChinookDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerID",
            "dataType": "int64",
            "sourceColumn": "CustomerID"
          },
          {
            "name": "CustomerFirstName",
            "dataType": "string",
            "sourceColumn": "CustomerFirstName"
          },
          {
            "name": "CustomerLastName",
            "dataType": "string",
            "sourceColumn": "CustomerLastName"
          },
          {
            "name": "CustomerCompany",
            "dataType": "string",
            "sourceColumn": "CustomerCompany"
          },
          {
            "name": "CustomerCity",
            "dataType": "string",
            "sourceColumn": "CustomerCity"
          },
          {
            "name": "CustomerState",
            "dataType": "string",
            "sourceColumn": "CustomerState"
          },
          {
            "name": "CustomerCountry",
            "dataType": "string",
            "sourceColumn": "CustomerCountry"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "name": "RowChangeReason",
            "dataType": "string",
            "sourceColumn": "RowChangeReason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "SalesPerformance2010",
            "expression": " (CALCULATE(SUM(FactSales[InvoiceUnitPrice]), YEAR(DimDate[Date])=2010)/CALCULATE(SUM(FactSales[InvoiceUnitPrice]),YEAR(DimDate[Date])=2009) - 1) * 100",
            "kpi": {
              "targetExpression": "5",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='DimCustomer'[SalesPerformance2010] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0,-1,",
                "\t                If(x<3,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "3"
                }
              ]
            }
          },
          {
            "name": "SalesPerformance2011",
            "expression": " (CALCULATE(SUM(FactSales[InvoiceUnitPrice]), YEAR(DimDate[Date])=2011)/CALCULATE(SUM(FactSales[InvoiceUnitPrice]),YEAR(DimDate[Date])=2010) - 1 ) * 100",
            "kpi": {
              "targetExpression": "5",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='DimCustomer'[SalesPerformance2011] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0,-1,",
                "\t                If(x<3,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "3"
                }
              ]
            }
          },
          {
            "name": "SalesPerformance2012",
            "expression": " (CALCULATE(SUM(FactSales[InvoiceUnitPrice]), YEAR(DimDate[Date])=2012)/CALCULATE(SUM(FactSales[InvoiceUnitPrice]),YEAR(DimDate[Date])=2011) - 1)  * 100",
            "kpi": {
              "targetExpression": "5",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='DimCustomer'[SalesPerformance2012] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0,-1,",
                "\t                If(x<3,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "3"
                }
              ]
            }
          },
          {
            "name": "SalesPerformance2013",
            "expression": " (CALCULATE(SUM(FactSales[InvoiceUnitPrice]), YEAR(DimDate[Date])=2013)/CALCULATE(SUM(FactSales[InvoiceUnitPrice]),YEAR(DimDate[Date])=2012) - 1 ) * 100",
            "kpi": {
              "targetExpression": "5",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='DimCustomer'[SalesPerformance2013] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0,-1,",
                "\t                If(x<3,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "3"
                }
              ]
            }
          },
          {
            "name": "TotalSales",
            "expression": "  CALCULATE(SUM(FactSales[InvoiceUnitPrice]))"
          },
          {
            "name": "TracksSold",
            "expression": " COUNT(FactSales[InvoiceKey])"
          },
          {
            "name": "AverageSalePrice",
            "expression": " CALCULATE(AVERAGE(FactSales[InvoiceTotalPrice]))"
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "FullDateUK",
            "dataType": "string",
            "sourceColumn": "FullDateUK"
          },
          {
            "name": "FullDateUSA",
            "dataType": "string",
            "sourceColumn": "FullDateUSA"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeekUSA",
            "dataType": "string",
            "sourceColumn": "DayOfWeekUSA"
          },
          {
            "name": "DayOfWeekUK",
            "dataType": "string",
            "sourceColumn": "DayOfWeekUK"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "string",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "string",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "string",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "string",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "string",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "IsHolidayUSA",
            "dataType": "boolean",
            "sourceColumn": "IsHolidayUSA"
          },
          {
            "name": "IsWeekday",
            "dataType": "boolean",
            "sourceColumn": "IsWeekday"
          },
          {
            "name": "HolidayUSA",
            "dataType": "string",
            "sourceColumn": "HolidayUSA"
          },
          {
            "name": "IsHolidayUK",
            "dataType": "boolean",
            "sourceColumn": "IsHolidayUK"
          },
          {
            "name": "HolidayUK",
            "dataType": "string",
            "sourceColumn": "HolidayUK"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeID",
            "dataType": "int64",
            "sourceColumn": "EmployeeID"
          },
          {
            "name": "EmployeeFirstName",
            "dataType": "string",
            "sourceColumn": "EmployeeFirstName"
          },
          {
            "name": "EmployeeLastName",
            "dataType": "string",
            "sourceColumn": "EmployeeLastName"
          },
          {
            "name": "EmployeeTitle",
            "dataType": "string",
            "sourceColumn": "EmployeeTitle"
          },
          {
            "name": "EmployeeCity",
            "dataType": "string",
            "sourceColumn": "EmployeeCity"
          },
          {
            "name": "EmployeeState",
            "dataType": "string",
            "sourceColumn": "EmployeeState"
          },
          {
            "name": "EmployeeCountry",
            "dataType": "string",
            "sourceColumn": "EmployeeCountry"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "name": "RowChangeReason",
            "dataType": "string",
            "sourceColumn": "RowChangeReason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPlaylist",
        "columns": [
          {
            "name": "PlaylistKey",
            "dataType": "int64",
            "sourceColumn": "PlaylistKey"
          },
          {
            "name": "PlaylistID",
            "dataType": "int64",
            "sourceColumn": "PlaylistID"
          },
          {
            "name": "PlaylistName",
            "dataType": "string",
            "sourceColumn": "PlaylistName"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "name": "RowChangeReason",
            "dataType": "string",
            "sourceColumn": "RowChangeReason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_DimPlaylist = Source{[Schema=\"dbo\",Item=\"DimPlaylist\"]}[Data]",
                "in",
                "    dbo_DimPlaylist"
              ]
            }
          }
        ]
      },
      {
        "name": "DimTrack",
        "columns": [
          {
            "name": "TrackKey",
            "dataType": "int64",
            "sourceColumn": "TrackKey"
          },
          {
            "name": "TrackID",
            "dataType": "int64",
            "sourceColumn": "TrackID"
          },
          {
            "name": "TrackName",
            "dataType": "string",
            "sourceColumn": "TrackName"
          },
          {
            "name": "Composer",
            "dataType": "string",
            "sourceColumn": "Composer"
          },
          {
            "name": "Bytes",
            "dataType": "int64",
            "sourceColumn": "Bytes"
          },
          {
            "name": "Milliseconds",
            "dataType": "int64",
            "sourceColumn": "Milliseconds"
          },
          {
            "name": "TrackUnitPrice",
            "dataType": "double",
            "sourceColumn": "TrackUnitPrice"
          },
          {
            "name": "MediaTypeName",
            "dataType": "string",
            "sourceColumn": "MediaTypeName"
          },
          {
            "name": "GenreName",
            "dataType": "string",
            "sourceColumn": "GenreName"
          },
          {
            "name": "AlbumTitle",
            "dataType": "string",
            "sourceColumn": "AlbumTitle"
          },
          {
            "name": "ArtistName",
            "dataType": "string",
            "sourceColumn": "ArtistName"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "name": "RowChangeReason",
            "dataType": "string",
            "sourceColumn": "RowChangeReason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_DimTrack = Source{[Schema=\"dbo\",Item=\"DimTrack\"]}[Data]",
                "in",
                "    dbo_DimTrack"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "InvoiceKey",
            "dataType": "int64",
            "sourceColumn": "InvoiceKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "TrackKey",
            "dataType": "int64",
            "sourceColumn": "TrackKey"
          },
          {
            "name": "InvoiceDateKey",
            "dataType": "int64",
            "sourceColumn": "InvoiceDateKey"
          },
          {
            "name": "InvoiceTotalPrice",
            "dataType": "double",
            "sourceColumn": "InvoiceTotalPrice"
          },
          {
            "name": "InvoiceUnitPrice",
            "dataType": "double",
            "sourceColumn": "InvoiceUnitPrice"
          },
          {
            "name": "InvoiceQuantity",
            "dataType": "int64",
            "sourceColumn": "InvoiceQuantity"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data]",
                "in",
                "    dbo_FactSales"
              ]
            }
          }
        ]
      },
      {
        "name": "PlaylistTrack",
        "columns": [
          {
            "name": "PlaylistKey",
            "dataType": "int64",
            "sourceColumn": "PlaylistKey"
          },
          {
            "name": "TrackKey",
            "dataType": "int64",
            "sourceColumn": "TrackKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;ChinookDW\",",
                "    dbo_PlaylistTrack = Source{[Schema=\"dbo\",Item=\"PlaylistTrack\"]}[Data]",
                "in",
                "    dbo_PlaylistTrack"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "2c78d365-0556-4362-b504-dab8f86917b1",
        "fromTable": "FactSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "811e8b51-0d17-4470-b07e-02d1fbb4ba1c",
        "fromTable": "FactSales",
        "fromColumn": "InvoiceDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "0015c726-447b-438d-aeb1-5db48f3c2b5e",
        "fromTable": "FactSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "adf6ec63-3a48-499b-953a-845331a999b4",
        "fromTable": "PlaylistTrack",
        "fromColumn": "PlaylistKey",
        "toTable": "DimPlaylist",
        "toColumn": "PlaylistKey"
      },
      {
        "name": "ac86fba8-271d-488a-bae8-110b383ca27a",
        "fromTable": "FactSales",
        "fromColumn": "TrackKey",
        "toTable": "DimTrack",
        "toColumn": "TrackKey"
      },
      {
        "name": "e7e81148-e049-4407-a041-b2ac3d0e2fb4",
        "fromTable": "PlaylistTrack",
        "fromColumn": "TrackKey",
        "toTable": "DimTrack",
        "toColumn": "TrackKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}